# Generated by Django 5.2.3 on 2025-10-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_acessorios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessorios',
            new_name='Acessorio',
        ),
    ]
