# Generated by Django 5.2.3 on 2025-07-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Cliente', max_length=200)),
                ('checkbox_1', models.BooleanField(default=False, verbose_name='Venda 1')),
                ('data_checkbox_1', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 1')),
                ('checkbox_2', models.BooleanField(default=False, verbose_name='Venda 2')),
                ('data_checkbox_2', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 2')),
                ('checkbox_3', models.BooleanField(default=False, verbose_name='Venda 3')),
                ('data_checkbox_3', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 3')),
                ('checkbox_4', models.BooleanField(default=False, verbose_name='Venda 4')),
                ('data_checkbox_4', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 4')),
                ('checkbox_5', models.BooleanField(default=False, verbose_name='Venda 5')),
                ('data_checkbox_5', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 5')),
                ('checkbox_6', models.BooleanField(default=False, verbose_name='Venda 6')),
                ('data_checkbox_6', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 6')),
                ('checkbox_7', models.BooleanField(default=False, verbose_name='Venda 7')),
                ('data_checkbox_7', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 7')),
                ('checkbox_8', models.BooleanField(default=False, verbose_name='Venda 8')),
                ('data_checkbox_8', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 8')),
                ('checkbox_9', models.BooleanField(default=False, verbose_name='Venda 9')),
                ('data_checkbox_9', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 9')),
                ('checkbox_10', models.BooleanField(default=False, verbose_name='Venda 10')),
                ('data_checkbox_10', models.DateTimeField(blank=True, null=True, verbose_name='Data Venda 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartão Fidelidade',
                'verbose_name_plural': 'Cartão Fidelidade',
            },
        ),
    ]
