# Generated by Django 5.2.3 on 2025-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxsell',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
