FROM python:3.11-slim

WORKDIR /sistema_bellafly

COPY requirements.txt /sistema_bellafly/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /sistema_bellafly/

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
